# Generated by Django 4.2 on 2026-01-05 13:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('spiral', 'Spiral Drawing'), ('voice', 'Voice Recording'), ('mri', 'MRI Scan'), ('quiz', 'Symptom Quiz'), ('video', 'Posture Video')], max_length=10)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('parkinson_prediction', models.BooleanField(default=False)),
                ('parkinson_stage', models.IntegerField(blank=True, choices=[(0, "No Parkinson's"), (1, 'Stage 1 - Unilateral symptoms'), (2, 'Stage 2 - Bilateral symptoms, balance intact'), (3, 'Stage 3 - Balance impairment'), (4, 'Stage 4 - Severe disability'), (5, 'Stage 5 - Wheelchair bound or bedridden')], null=True)),
                ('confidence_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('severity_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_taken'],
            },
        ),
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='voice_recordings/')),
                ('duration', models.FloatField(blank=True, null=True)),
                ('pitch_variation', models.FloatField(blank=True, null=True)),
                ('jitter', models.FloatField(blank=True, null=True)),
                ('shimmer', models.FloatField(blank=True, null=True)),
                ('hnr', models.FloatField(blank=True, null=True)),
                ('mfcc_features', models.JSONField(blank=True, null=True)),
                ('speech_rate', models.FloatField(blank=True, null=True)),
                ('articulation_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_recording', to='assessments.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='SymptomQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tremor', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('bradykinesia', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('rigidity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('postural_instability', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('sleep_problems', models.BooleanField(default=False)),
                ('depression', models.BooleanField(default=False)),
                ('anxiety', models.BooleanField(default=False)),
                ('cognitive_changes', models.BooleanField(default=False)),
                ('daily_activities', models.IntegerField(default=0, help_text='0=Normal, 4=Severe difficulty', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('symptom_duration', models.IntegerField(choices=[(1, '<6 months'), (2, '6-12 months'), (3, '1-2 years'), (4, '>2 years')], default=1)),
                ('additional_notes', models.TextField(blank=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_quiz', to='assessments.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='SpiralDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_image', models.ImageField(upload_to='spiral_drawings/')),
                ('drawing_data', models.JSONField(blank=True, null=True)),
                ('smoothness_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('tremor_frequency', models.FloatField(blank=True, null=True)),
                ('amplitude_variation', models.FloatField(blank=True, null=True)),
                ('symmetry_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('ai_analysis', models.JSONField(blank=True, null=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spiral_drawing', to='assessments.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='PostureVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='posture_videos/')),
                ('duration', models.FloatField(blank=True, null=True)),
                ('stride_length', models.FloatField(blank=True, null=True)),
                ('gait_speed', models.FloatField(blank=True, null=True)),
                ('step_width', models.FloatField(blank=True, null=True)),
                ('arm_swing', models.FloatField(blank=True, null=True)),
                ('posture_stability', models.FloatField(blank=True, null=True)),
                ('trunk_flexion', models.FloatField(blank=True, null=True)),
                ('balance_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('movement_features', models.JSONField(blank=True, null=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posture_video', to='assessments.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('overall_severity', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('spiral_score', models.FloatField(blank=True, null=True)),
                ('voice_score', models.FloatField(blank=True, null=True)),
                ('mri_score', models.FloatField(blank=True, null=True)),
                ('quiz_score', models.FloatField(blank=True, null=True)),
                ('posture_score', models.FloatField(blank=True, null=True)),
                ('prediction', models.CharField(default='Pending', max_length=50)),
                ('recommendation', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Patient Histories',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='MRIScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_image', models.ImageField(upload_to='mri_scans/')),
                ('scan_type', models.CharField(default='T1-weighted', max_length=50)),
                ('nigra_volume', models.FloatField(blank=True, null=True)),
                ('caudate_volume', models.FloatField(blank=True, null=True)),
                ('putamen_volume', models.FloatField(blank=True, null=True)),
                ('asymmetry_index', models.FloatField(blank=True, null=True)),
                ('cnn_confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('detected_abnormalities', models.JSONField(blank=True, null=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mri_scan', to='assessments.assessment')),
            ],
        ),
    ]
