# Generated by Django 4.2 on 2026-01-06 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('spiral', 'Spiral Drawing Model'), ('voice', 'Voice Analysis Model'), ('mri', 'MRI Scan Model'), ('quiz', 'Quiz Scoring Model'), ('ensemble', 'Ensemble Model')], max_length=20)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('accuracy', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('trained', 'Trained'), ('training', 'Training'), ('untrained', 'Untrained'), ('failed', 'Training Failed')], default='untrained', max_length=20)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='ai_models/')),
                ('scaler_file', models.FileField(blank=True, null=True, upload_to='ai_scalers/')),
                ('feature_columns', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('probabilities', models.JSONField(default=dict)),
                ('features_used', models.JSONField(default=list)),
                ('prediction_time', models.FloatField(help_text='Prediction time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prediction', to='assessments.assessment')),
                ('model_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_models.aimodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelTrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_size', models.IntegerField()),
                ('training_duration', models.FloatField(help_text='Duration in seconds')),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('metrics', models.JSONField(default=dict)),
                ('training_log', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('running', 'Running')], max_length=20)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_logs', to='ai_models.aimodel')),
            ],
            options={
                'ordering': ['-training_date'],
            },
        ),
    ]
